### ISSUE TITLE
Почему нету релиза в который можно зайти и протестить? 

### ISSUE THREAD

**Issue by steelswing** [GeneralPashon/open-miner#1]
Почему нету релиза в который можно зайти и протестить?

**Comment by GeneralPashon** [comment]
Проект новый, до релиза еще далеко. Пока нет релиза его можно запустить в IDEA, перед этим нужно выполнить mvn install в [Jpize-engine](https://github.com/GeneralPashon/jpize-engine). Однако запускать там пока особо нечего
